export const APP_DATA_ACTION = {
  GET_TASK_SELECTION_STEPS: 'GET_TASK_SELECTION_STEPS',
  GET_TASK_SELECTION_STATUS: 'GET_TASK_SELECTION_STATUS',
  GET_TASK_ASSIGNEES: 'GET_TASK_ASSIGNEES',
  GET_JOBSITES: 'GET_JOBSITES',
  GET_OCCUPATIONS: 'GET_OCCUPATIONS',
  GET_ALL_APP_DATA: 'GET_ALL_APP_DATA',
  GET_JOB_OFFER: 'GET_JOB_OFFER'
};
