export const AUTH_ACTION = {
  GET_CURRENT_INFO: 'GET_CURRENT_INFO',
  LOGIN: 'AUTH_LOGIN',
  GET_SESSION: 'AUTH_GET_SESSION',
  LOGOUT: 'AUTH_LOGOUT',
  CLEAR_AUTH: 'CLEAR_AUTH',
  ERROR_MESSAGE: 'AUTH_ERROR_MESSAGE',
  REGISTER: 'AUTH_REGISTER',
  NEWPASSWORD: 'AUTH_NEWPASSWORD'
};
